label: 'Az ehhez az indexhez használt feldolgozók'
tips:
  search-api-index-processors-introduction:
    label: 'Az ehhez az indexhez használt feldolgozók'
  search-api-index-processors-enable:
    label: 'Feldolgozók engedélyezése'
  search-api-index-processors-weights:
    label: 'Feldolgozó sorrend'
  search-api-index-processors-settings:
    label: 'Feldolgozó beállítások'
    body: 'Néhány feldolgozóhoz további beállítások érhetőek el melyeket itt lehet módosítani.'
