display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Wyszukaj
      fields:
        nid:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
      empty:
        area_text_custom:
          content: 'Brak wyników'
  page_1:
    display_options:
      title: 'Filmy o Napo'
      exposed_form:
        options:
          submit_button: Wyszukaj
  page_2:
    display_options:
      fields:
        nid:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        url_1:
          alter:
            text: 'Zobacz film'
        nothing:
          alter:
            text: "<div class=\"item\">\r\n    <div class=\"napo-film-title-container\">\r\n         <h3>{{title}}</h3>\r\n         <div class=\"download-video\"><a target=\"_blank\" href=\"{{ uri}}\">Pobierz plik wideo</a></div>\r\n         <div class=\"cart\">{{content_cart}}<a href=\"#\">Dodaj do centrum pobierania</a></div>\r\n    </div>\r\n    <div class=\"napo-film-list-image\">\r\n        {{field_image}}\r\n    </div>\r\n    <div class=\"napo-film-content-container\">\r\n        <div class=\"grid date\">{{field_publication_date}}</div>\r\n        <p class=\"grid text\">{{processed}}</p>\r\n        <div class=\"grid tags\">{{ field_combined_tags }}</div>\r\n        <div class=\"view-video\">{{ url_1 }}</div>\r\n        <div class=\"view-scenes\"><a href=\"/napo-s-film-episodes/{{nid}}\">Zobacz odcinki</a></div>\r\n    </div>\r\n</div>"
  page_list:
    display_options:
      fields:
        nid:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        url_1:
          alter:
            text: 'Zobacz film'
        nothing:
          alter:
            text: "<div class=\"item\">\r\n<div class=\"cart\">{{content_cart}}<a href=\"#\">Dodaj do centrum pobierania</a></div>\r\n<div class=\"napo-film-list-image\">{{field_image}}</div>\r\n<div class=\"group-right\">\r\n<h3>{{title}}</h3>\r\n<div>{{field_publication_date}}</div>\r\n<p>{{processed}}</p>\r\n<div class=\"napo-film-list-details-container\">\r\n<div class=\"\">{{ field_combined_tags }} </div>\r\n<div class=\"view-scenes\"><a href=\"/napo-s-film-episodes/{{nid}}\">Zobacz odcinki</a></div>\r\n<div class=\"view-video\">{{ url_1 }}</div>\r\n<div class=\"download-video\"><a target=\"_blank\" href=\"{{ uri}}\">Pobierz plik wideo</a></div>\r\n\r\n</div>\r\n</div>\r\n</div>"
