_core:
  default_config_hash: GLswejPT_b3G9TtpI4NKwR1mhIB_-FnysNn9QKc-01w
general:
  page_cache_maximum_age: '3600'
  noise: ''
  debug: '0'
  logging: '0'
  secret: b9f79bf8-8f98-41fc-9d6c-e816cb4ce0d6
  varnish_server: 'https://www.napofilm.net'
  varnish_purger: true
  purger_maintenance_mode: false
  grace: '1800'
available:
  enable_cache: true
  authenticated_users: false
  esi: false
  esi_purge_user_blocks: false
  excluded_urls: ''
cache_control:
  anonymous: '/user/logout|must-revalidate, no-cache, private'
  authenticated: ''
